# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-08 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='firs_name',
            new_name='first_name',
        ),
    ]
