# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-09 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studdb', '0002_auto_20160608_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='studdb.Student', verbose_name='Monitor'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studdb.Group', verbose_name='Group'),
        ),
    ]
